# Generated by Django 2.2.10 on 2020-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField(max_length=40)),
                ('news_title', models.TextField(max_length=2000)),
                ('img_source_url', models.TextField(max_length=500)),
                ('author', models.TextField(max_length=20)),
            ],
        ),
    ]
